 gap: "16px",
    marginTop: "20px",
  },
  scoreBox: {
    background: "#ecfdf5",
    border: "1px solid #10b981",
    color: "#064e3b",
    padding: "18px",
    borderRadius: "16px",
    fontSize: "20px",
    marginTop: "24px",
  },
  questionCard: {
    marginTop: "24px",
    border: "1px solid #e5e7eb",
    borderRadius: "20px",
    padding: "22px",
    background: "#f8fafc",
  },
  questionHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "12px",
    alignItems: "center",
  },
  questionTitle: {
    color: "#064e3b",
    fontSize: "20px",
    margin: 0,
  },
  scoreSmall: {
    background: "#047857",
    color: "white",
    padding: "10px 14px",
    borderRadius: "12px",
    fontWeight: "bold",
    whiteSpace: "nowrap",
  },
  options: {
    display: "grid",
    gap: "12px",
    marginTop: "18px",
  },
  radioLabel: {
    display: "flex",
    gap: "10px",
    alignItems: "center",
    background: "white",
    padding: "14px",
    borderRadius: "12px",
    border: "1px solid #e5e7eb",
    fontWeight: "bold",
  },
};
